@extends('products.layout')

@section('content')

<div class="container-fluid py-4">

    {{-- Header --}}
    <div class="d-flex flex-wrap justify-content-between align-items-center mb-4 gap-3">

        <div>
            <h2 class="fw-bold mb-1">
                <i class="bi bi-bell-fill me-2"></i>
                Event Notification Center
            </h2>

            <p class="text-muted mb-0">
                Monitor product events generated by custom model observers.
            </p>
        </div>

        <div class="d-flex gap-2">

            <button
                type="button"
                class="btn btn-outline-primary"
                id="markAllReadBtn"
                {{ $unreadCount === 0 ? 'disabled' : '' }}
            >
                <i class="bi bi-check2-all me-1"></i>
                Mark All Read
            </button>

            <button
                type="button"
                class="btn btn-outline-danger"
                id="clearAllBtn"
                {{ $notifications->total() === 0 ? 'disabled' : '' }}
            >
                <i class="bi bi-trash me-1"></i>
                Clear All
            </button>

        </div>

    </div>


    {{-- Statistics --}}
    <div class="row g-3 mb-4">

        <div class="col-md-6 col-lg-3">
            <div class="card border-0 shadow-sm h-100">
                <div class="card-body">

                    <div class="d-flex justify-content-between">

                        <div>
                            <div class="text-muted small">
                                Total Notifications
                            </div>

                            <h3 class="fw-bold mb-0">
                                {{ $notifications->total() }}
                            </h3>
                        </div>

                        <div class="fs-2 text-primary">
                            <i class="bi bi-bell"></i>
                        </div>

                    </div>

                </div>
            </div>
        </div>


        <div class="col-md-6 col-lg-3">
            <div class="card border-0 shadow-sm h-100">
                <div class="card-body">

                    <div class="d-flex justify-content-between">

                        <div>
                            <div class="text-muted small">
                                Unread
                            </div>

                            <h3
                                class="fw-bold mb-0"
                                id="notificationUnreadStat"
                            >
                                {{ $unreadCount }}
                            </h3>
                        </div>

                        <div class="fs-2 text-danger">
                            <i class="bi bi-envelope"></i>
                        </div>

                    </div>

                </div>
            </div>
        </div>


        <div class="col-md-6 col-lg-3">
            <div class="card border-0 shadow-sm h-100">
                <div class="card-body">

                    <div class="d-flex justify-content-between">

                        <div>
                            <div class="text-muted small">
                                Status Events
                            </div>

                            <h3 class="fw-bold mb-0">
                                {{ $eventCounts->get('statusChanged', 0) }}
                            </h3>
                        </div>

                        <div class="fs-2 text-info">
                            <i class="bi bi-arrow-repeat"></i>
                        </div>

                    </div>

                </div>
            </div>
        </div>


        <div class="col-md-6 col-lg-3">
            <div class="card border-0 shadow-sm h-100">
                <div class="card-body">

                    <div class="d-flex justify-content-between">

                        <div>
                            <div class="text-muted small">
                                Price Changes
                            </div>

                            <h3 class="fw-bold mb-0">
                                {{ $eventCounts->get('priceChanged', 0) }}
                            </h3>
                        </div>

                        <div class="fs-2 text-success">
                            <i class="bi bi-currency-rupee"></i>
                        </div>

                    </div>

                </div>
            </div>
        </div>

    </div>


    {{-- Filters --}}
    <div class="card border-0 shadow-sm mb-4">

        <div class="card-body">

            <form
                method="GET"
                action="{{ route('notifications.index') }}"
                class="row g-3 align-items-end"
            >

                <div class="col-md-4">

                    <label class="form-label fw-semibold">
                        Event Type
                    </label>

                    <select
                        name="event"
                        class="form-select"
                    >

                        <option value="">
                            All Events
                        </option>

                        <option
                            value="activated"
                            {{ $event === 'activated' ? 'selected' : '' }}
                        >
                            Activated
                        </option>

                        <option
                            value="deactivated"
                            {{ $event === 'deactivated' ? 'selected' : '' }}
                        >
                            Deactivated
                        </option>

                        <option
                            value="archived"
                            {{ $event === 'archived' ? 'selected' : '' }}
                        >
                            Archived
                        </option>

                        <option
                            value="statusChanged"
                            {{ $event === 'statusChanged' ? 'selected' : '' }}
                        >
                            Status Changed
                        </option>

                        <option
                            value="priceChanged"
                            {{ $event === 'priceChanged' ? 'selected' : '' }}
                        >
                            Price Changed
                        </option>

                    </select>

                </div>


                <div class="col-md-auto">

                    <button class="btn btn-primary">

                        <i class="bi bi-funnel me-1"></i>
                        Apply Filter

                    </button>

                </div>


                <div class="col-md-auto">

                    <a
                        href="{{ route('notifications.index') }}"
                        class="btn btn-outline-secondary"
                    >

                        <i class="bi bi-x-circle me-1"></i>
                        Clear

                    </a>

                </div>

            </form>

        </div>

    </div>


    {{-- Notifications --}}
    <div class="card border-0 shadow-sm">

        <div class="card-header bg-white py-3">

            <div class="d-flex justify-content-between align-items-center">

                <h5 class="mb-0 fw-bold">
                    Recent Events
                </h5>

                <span class="badge bg-primary">
                    {{ $notifications->total() }}
                </span>

            </div>

        </div>


        <div class="card-body p-0">

            @if($notifications->count() > 0)

                <div class="list-group list-group-flush">

                    @foreach($notifications as $notification)

                        <div
                            class="list-group-item notification-item
                            {{ !$notification->is_read ? 'notification-unread' : '' }}"
                            data-id="{{ $notification->id }}"
                        >

                            <div class="d-flex gap-3 align-items-start">

                                {{-- Icon --}}
                                <div
                                    class="notification-icon
                                    bg-{{ $notification->event_badge }}"
                                >

                                    <i
                                        class="bi {{ $notification->event_icon }}"
                                    ></i>

                                </div>


                                {{-- Content --}}
                                <div class="flex-grow-1">

                                    <div class="d-flex flex-wrap justify-content-between gap-2">

                                        <div>

                                            <h6 class="fw-bold mb-1">

                                                {{ $notification->title }}

                                                @if(!$notification->is_read)

                                                    <span class="badge bg-primary ms-1">
                                                        New
                                                    </span>

                                                @endif

                                            </h6>

                                            <div class="text-muted small">

                                                Product:
                                                <strong>
                                                    {{ $notification->product?->name ?? 'Deleted Product' }}
                                                </strong>

                                            </div>

                                        </div>


                                        <span
                                            class="badge bg-{{ $notification->event_badge }}"
                                        >
                                            {{ $notification->event }}
                                        </span>

                                    </div>


                                    <p class="mb-2 mt-2">
                                        {{ $notification->message }}
                                    </p>


                                    <div class="d-flex flex-wrap align-items-center gap-2">

                                        <small class="text-muted">

                                            <i class="bi bi-clock me-1"></i>

                                            {{ $notification->created_at->diffForHumans() }}

                                        </small>


                                        @if(!$notification->is_read)

                                            <button
                                                type="button"
                                                class="btn btn-sm btn-outline-primary mark-read-btn"
                                                data-id="{{ $notification->id }}"
                                            >

                                                <i class="bi bi-check2 me-1"></i>
                                                Mark Read

                                            </button>

                                        @endif


                                        <button
                                            type="button"
                                            class="btn btn-sm btn-outline-danger delete-notification-btn"
                                            data-id="{{ $notification->id }}"
                                        >

                                            <i class="bi bi-trash me-1"></i>
                                            Delete

                                        </button>

                                    </div>

                                </div>

                            </div>

                        </div>

                    @endforeach

                </div>

            @else

                <div class="text-center py-5">

                    <div class="display-4 text-muted mb-3">
                        <i class="bi bi-bell-slash"></i>
                    </div>

                    <h5>
                        No notifications found
                    </h5>

                    <p class="text-muted mb-0">
                        Product events will appear here automatically.
                    </p>

                </div>

            @endif

        </div>

    </div>


    {{-- Pagination --}}
    @if($notifications->hasPages())

        <div class="mt-4">
            {{ $notifications->links() }}
        </div>

    @endif

</div>

@endsection


@push('styles')

<style>

    .notification-item {
        padding: 20px;
        transition: background-color 0.2s ease;
    }

    .notification-item:hover {
        background-color: #f8f9fa;
    }

    .notification-unread {
        background-color: #f0f7ff;
        border-left: 4px solid #0d6efd;
    }

    .notification-icon {
        width: 48px;
        height: 48px;
        min-width: 48px;
        border-radius: 50%;
        display: flex;
        align-items: center;
        justify-content: center;
        color: #fff;
        font-size: 20px;
    }

</style>

@endpush


@push('scripts')

<script>

document.addEventListener('DOMContentLoaded', function () {

    const csrfToken =
        document.querySelector('meta[name="csrf-token"]').getAttribute('content');

    const unreadStat =
        document.getElementById('notificationUnreadStat');

    const markAllReadBtn =
        document.getElementById('markAllReadBtn');

    const clearAllBtn =
        document.getElementById('clearAllBtn');


    function updateUnreadCount(count) {

        if (unreadStat) {
            unreadStat.textContent = count;
        }

        if (markAllReadBtn) {
            markAllReadBtn.disabled = count === 0;
        }

        const navbarBadge =
            document.getElementById('notificationBadge');

        if (navbarBadge) {

            navbarBadge.textContent = count;

            navbarBadge.style.display =
                count > 0 ? 'inline-block' : 'none';
        }
    }


    /*
    |--------------------------------------------------------------------------
    | Mark Single Notification As Read
    |--------------------------------------------------------------------------
    */

    document.querySelectorAll('.mark-read-btn').forEach(button => {

        button.addEventListener('click', function () {

            const id = this.dataset.id;

            fetch(`/notifications/${id}/read`, {

                method: 'PATCH',

                headers: {
                    'X-CSRF-TOKEN': csrfToken,
                    'Accept': 'application/json',
                }

            })
            .then(response => response.json())
            .then(data => {

                if (data.success) {

                    const item =
                        document.querySelector(
                            `.notification-item[data-id="${id}"]`
                        );

                    if (item) {

                        item.classList.remove(
                            'notification-unread'
                        );

                        const newBadge =
                            item.querySelector('.badge.bg-primary');

                        if (newBadge &&
                            newBadge.textContent.trim() === 'New') {

                            newBadge.remove();
                        }

                        this.remove();
                    }

                    updateUnreadCount(data.unread_count);
                }

            })
            .catch(error => {

                console.error(
                    'Mark read error:',
                    error
                );

            });

        });

    });


    /*
    |--------------------------------------------------------------------------
    | Mark All As Read
    |--------------------------------------------------------------------------
    */

    if (markAllReadBtn) {

        markAllReadBtn.addEventListener('click', function () {

            fetch('{{ route('notifications.mark-all-read') }}', {

                method: 'PATCH',

                headers: {
                    'X-CSRF-TOKEN': csrfToken,
                    'Accept': 'application/json',
                }

            })
            .then(response => response.json())
            .then(data => {

                if (data.success) {

                    document
                        .querySelectorAll('.notification-unread')
                        .forEach(item => {

                            item.classList.remove(
                                'notification-unread'
                            );

                        });

                    document
                        .querySelectorAll('.mark-read-btn')
                        .forEach(button => {

                            button.remove();

                        });

                    updateUnreadCount(
                        data.unread_count
                    );
                }

            })
            .catch(error => {

                console.error(
                    'Mark all read error:',
                    error
                );

            });

        });

    }


    /*
    |--------------------------------------------------------------------------
    | Delete Notification
    |--------------------------------------------------------------------------
    */

    document
        .querySelectorAll('.delete-notification-btn')
        .forEach(button => {

            button.addEventListener('click', function () {

                const id = this.dataset.id;

                if (!confirm(
                    'Delete this notification?'
                )) {
                    return;
                }

                fetch(`/notifications/${id}`, {

                    method: 'DELETE',

                    headers: {
                        'X-CSRF-TOKEN': csrfToken,
                        'Accept': 'application/json',
                    }

                })
                .then(response => response.json())
                .then(data => {

                    if (data.success) {

                        const item =
                            document.querySelector(
                                `.notification-item[data-id="${id}"]`
                            );

                        if (item) {
                            item.remove();
                        }

                        updateUnreadCount(
                            data.unread_count
                        );
                    }

                })
                .catch(error => {

                    console.error(
                        'Delete notification error:',
                        error
                    );

                });

            });

        });


    /*
    |--------------------------------------------------------------------------
    | Clear All
    |--------------------------------------------------------------------------
    */

    if (clearAllBtn) {

        clearAllBtn.addEventListener('click', function () {

            if (!confirm(
                'Clear all notifications?'
            )) {
                return;
            }

            fetch('{{ route('notifications.clear-all') }}', {

                method: 'DELETE',

                headers: {
                    'X-CSRF-TOKEN': csrfToken,
                    'Accept': 'application/json',
                }

            })
            .then(response => response.json())
            .then(data => {

                if (data.success) {

                    window.location.reload();

                }

            })
            .catch(error => {

                console.error(
                    'Clear notifications error:',
                    error
                );

            });

        });

    }

});

</script>

@endpush